# Generated by Django 4.2.8 on 2024-05-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('economic_word', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
