# Generated by Django 4.2.8 on 2024-05-18 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.CharField(max_length=20, unique=True)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('homp_url', models.URLField()),
                ('cal_tel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=20, unique=True)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('join_way', models.CharField(max_length=200)),
                ('mtrt_int', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('join_deny', models.CharField(max_length=20)),
                ('join_member', models.CharField(max_length=100)),
                ('etc_note', models.TextField()),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('dcls_strt_day', models.CharField(max_length=10)),
                ('dcls_end_day', models.CharField(blank=True, max_length=10, null=True)),
                ('dcls_month', models.CharField(max_length=6)),
                ('fin_co_subm_day', models.CharField(max_length=20)),
                ('fin_co_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.bank')),
            ],
        ),
        migrations.CreateModel(
            name='SavingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=20, unique=True)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('join_way', models.CharField(max_length=200)),
                ('mtrt_int', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('join_deny', models.CharField(max_length=20)),
                ('join_member', models.CharField(max_length=100)),
                ('etc_note', models.TextField()),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('dcls_strt_day', models.CharField(max_length=10)),
                ('dcls_end_day', models.CharField(blank=True, max_length=10, null=True)),
                ('dcls_month', models.CharField(max_length=6)),
                ('fin_co_subm_day', models.CharField(max_length=20)),
                ('fin_co_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.bank')),
            ],
        ),
        migrations.CreateModel(
            name='SavingProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(max_length=100, verbose_name='저축 금리 유형')),
                ('intr_rate_type_nm', models.CharField(max_length=100, verbose_name='저축 금리 유형명')),
                ('rsrv_type', models.CharField(max_length=100, verbose_name='적립 유형')),
                ('rsrv_type_nm', models.CharField(max_length=100, verbose_name='적립 유형명')),
                ('save_trm', models.IntegerField(help_text='단위: 개월', verbose_name='저축 기간')),
                ('intr_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='저축 금리')),
                ('intr_rate2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='최고 우대금리')),
                ('saving_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_options', to='products.savingproduct')),
            ],
            options={
                'verbose_name': '저축 상품',
                'verbose_name_plural': '저축 상품 목록',
            },
        ),
        migrations.CreateModel(
            name='DepositProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(max_length=20)),
                ('intr_rate_type_nm', models.CharField(max_length=100)),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('intr_rate2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('deposit_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_options', to='products.depositproduct')),
            ],
        ),
        migrations.CreateModel(
            name='BankOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_cd', models.CharField(max_length=2)),
                ('area_nm', models.CharField(max_length=50)),
                ('exis_yn', models.CharField(max_length=1)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.bank')),
            ],
        ),
    ]
