# Generated by Django 4.2.8 on 2024-05-17 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=20, unique=True)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('join_way', models.CharField(max_length=200)),
                ('mtrt_int', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('join_deny', models.CharField(max_length=20)),
                ('join_member', models.CharField(max_length=100)),
                ('etc_note', models.TextField()),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('dcls_strt_day', models.DateField()),
                ('dcls_end_day', models.DateField(blank=True, null=True)),
                ('dcls_month', models.CharField(max_length=6)),
                ('fin_co_subm_day', models.DateTimeField()),
                ('fin_co_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.bank')),
            ],
        ),
        migrations.RenameModel(
            old_name='Option',
            new_name='BankOption',
        ),
        migrations.CreateModel(
            name='DepositProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(max_length=20)),
                ('intr_rate_type_nm', models.CharField(max_length=100)),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('intr_rate2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DepositProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.depositproduct')),
            ],
        ),
    ]
