# Generated by Django 4.2.8 on 2024-05-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensionproduct',
            name='sale_co',
            field=models.CharField(max_length=200),
        ),
    ]
