# Generated by Django 4.2.8 on 2024-05-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositproductoption',
            old_name='depoist_product',
            new_name='deposit_product',
        ),
    ]
