# Generated by Django 4.2.8 on 2024-05-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_depositproduct_depositproductoption_depoist_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproduct',
            name='dcls_strt_day',
            field=models.CharField(max_length=10),
        ),
    ]
