# Generated by Django 4.2.8 on 2024-05-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_depositproduct_dcls_strt_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproduct',
            name='fin_co_subm_day',
            field=models.CharField(max_length=20),
        ),
    ]
