# Generated by Django 4.2.8 on 2024-05-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_depositproduct_fin_co_subm_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproduct',
            name='dcls_end_day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
