# Generated by Django 4.2.8 on 2024-05-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_nm', models.CharField(default='', max_length=50)),
                ('cur_unit', models.CharField(max_length=50)),
                ('ttb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tts', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
