# Generated by Django 4.2.8 on 2024-05-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_nm', models.CharField(default='', max_length=50)),
                ('cur_unit', models.CharField(max_length=50)),
                ('deal_bas_r', models.CharField(max_length=20)),
            ],
        ),
    ]
